name: Build BusTracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: ["26.2"]
        name: ["iPhone 17 Pro"]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build BusTracker on iPhone Simulator
        run: |
          xcodebuild -scheme 'BusTracker' -destination 'platform=iOS Simulator,name=${{matrix.name}},OS=${{matrix.os}},arch=arm64'
