name: Build BusTracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: ["26.0", "26.0.1", "26.1", "26.2"]
        name:
          [
            "iPhone 17",
            "iPhone 17 Pro",
            "iPhone 17 Pro Max",
            "iPhone Air"
          ]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download platform
        run: |
          xcodebuild -downloadPlatform iOS -buildVersion ${{matrix.os}}  -architectureVariant arm64

      - name: Build BusTracker on iPhone Simulator
        run: |
          xcodebuild -scheme 'BusTracker' -destination 'platform=iOS Simulator,name=${{matrix.name}},OS=${{matrix.os}},arch=arm64'
