name: Build BusTracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-latest
    strategy:
      matrix:
        name:
          [
            "iPhone 16",
            "iPhone 16 Plus",
            "iPhone 16 Pro",
            "iPhone 16 Pro Max",
            "iPhone 16e",
            "iPhone 17",
            "iPhone 17 Pro",
            "iPhone 17 Pro Max",
            "iPhone Air",
          ]
        arch: ["arm64", "x86_64"]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List destinations
        run: |
          instruments -s devices

      - name: Build BusTracker on iPhone ${{matrix.iphone}} Simulator (iOS 26.5)
        run: |
          xcodebuild -scheme 'BusTracker' -destination 'platform=iOS Simulator,name=${{matrix.name}},arch=${{matrix.arch}}'
